- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"quarkus-petclinic:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"quarkus-petclinic\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: quarkus-petclinic
      app.kubernetes.io/component: quarkus-petclinic
      app.kubernetes.io/instance: quarkus-petclinic
    name: quarkus-petclinic
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: quarkus-petclinic
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: quarkus-petclinic
      spec:
        containers:
        - image: ' '
          name: quarkus-petclinic
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
  status: {}
